language: php

sudo: false

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
    - php: 7.1

before_install: composer selfupdate

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; composer update symfony/*; fi;
  - if [ "$SYMFONY_VERSION" = "" ]; then composer install; fi;

before_script: mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script: vendor/bin/coveralls -v
